allowBuilds:
  msgpackr-extract: true
  puppeteer: true
  sharp: true
  tesseract.js: true
  unrs-resolver: true
onlyBuiltDependencies:
  - msgpackr-extract
  - puppeteer
  - sharp
  - tesseract.js
  - unrs-resolver
