// Docs/Report-Disclaimer-and-Limitations.pdf — standard disclaimer text that
// must appear in every generated report, worded exactly as specified there
// (disclaimers are jurisdiction-sensitive; this wording should not be
// paraphrased independently in each generator). Centralized here so the
// full PDF, lite PDF, and AI executive summary generators all print
// identical text instead of three copies that can drift apart over time.

// A. Short version — cover (or score display) of every report, and the
// footer of the executive summary.
export const DISCLAIMER_SHORT =
  'This report is generated by automated scanning combined with defined review procedures and is provided for informational purposes only. It may contain errors or omissions, does not certify legal or regulatory compliance, and is not legal advice. Criteria marked Needs Review require assessment by a qualified accessibility specialist. See the Disclaimer and Limitations section for full terms. If you believe anything in this report is inaccurate, please contact us so we can review and correct it.';

// B. Full version — its own page at the end of every full report.
export const DISCLAIMER_FULL_TITLE = 'Disclaimer and Limitations';

export const DISCLAIMER_FULL_BODY =
  'Disclaimer and Limitations. This report was produced by the SilverSurfers.ai automated accessibility scanning platform, supplemented where stated by manual review. Portions of this report, including summaries and recommendations, are generated with automated and AI-assisted tooling and, despite quality controls, may contain errors, omissions, or findings that do not apply to your specific situation. Please verify important results before acting on them, and notify us of any suspected inaccuracy so we can review and correct it. This report reflects the state of the audited pages at the time of scanning only; websites change continuously and results may not describe the site at any later date. Scores are calculated under the SilverSurfers proprietary methodology and are a prioritization aid; they are not a conformance certification under WCAG, ADA, Section 508, the European Accessibility Act, EN 301 549, or any other standard or law. Automated testing can evaluate only a subset of accessibility requirements; success criteria marked Needs Review cannot be assessed automatically and require manual review by a qualified accessibility specialist. A passing score does not mean a website is accessible to all users or immune from complaints or claims, and a failing score does not by itself establish any legal violation. Nothing in this report constitutes legal advice, and no attorney-client relationship is created by it. For questions about legal exposure or regulatory obligations, consult qualified legal counsel. This report is prepared solely for the client named on the cover and for its internal use; SilverSurfers.ai accepts no responsibility to any third party who relies on it. To the maximum extent permitted by applicable law, SilverSurfers.ai, its owners, employees, and contractors shall not be liable for any loss, damage, claim, or expense arising from the use of, reliance on, or inability to use this report, and the total liability for any claim connected with a report shall not exceed the amount paid for that report. Use of this report constitutes acceptance of these terms.';

// C. One-line version — appended to the existing Stakeholder Note in every
// AI executive summary (the note itself stays; this sentence is added to it).
export const DISCLAIMER_AI_SENTENCE =
  'This summary is generated with AI assistance and may contain mistakes; please double-check important details against the full report, and tell us about anything that looks wrong so we can correct it.';

// "Next to every score" wording (Docs/WCAG-Manual-Review-Criteria.pdf, Section 6).
export const AUTOMATED_COVERAGE_SCORE_NOTE =
  'Automated results cover the criteria that can be machine-tested. Criteria marked Needs Review require manual review by a qualified accessibility specialist and are not included in automated pass/fail counts.';

export function appendStakeholderDisclaimer(stakeholderNote: string): string {
  const trimmed = (stakeholderNote || '').trim();
  return trimmed ? `${trimmed} ${DISCLAIMER_AI_SENTENCE}` : DISCLAIMER_AI_SENTENCE;
}

