export const WCAG_REMEDIATION_FALLBACKS: Record<string, string> = {
  "1.1.1": "Add meaningful alt text to all images; use empty alt=\"\" for purely decorative images.",
  "1.2.1": "Provide a text transcript for all pre-recorded audio-only and video-only media.",
  "1.2.2": "Add synchronized captions to all pre-recorded video content that includes audio.",
  "1.2.3": "Provide an audio description or full text alternative for all pre-recorded video content.",
  "1.2.4": "Provide live captions for all live video that includes spoken audio.",
  "1.2.5": "Add audio descriptions to all pre-recorded video where the soundtrack alone is insufficient.",
  "1.3.1": "Use semantic HTML (headings, lists, table headers) to expose structure to assistive technologies.",
  "1.3.2": "Ensure the reading and focus order of content matches the visual layout.",
  "1.3.3": "Never rely solely on sensory characteristics (color, shape, location) to identify page elements.",
  "1.3.4": "Remove CSS that locks the viewport to portrait or landscape; support both device orientations.",
  "1.3.5": "Add autocomplete attributes (e.g., name, email, tel) to all personal-data input fields.",
  "1.4.1": "Never use color alone to convey information; pair color cues with a text label or pattern.",
  "1.4.2": "Provide a pause/stop/mute control for any audio that auto-plays for more than 3 seconds.",
  "1.4.3": "Ensure body text meets a 4.5:1 contrast ratio and large text meets 3:1 against its background.",
  "1.4.4": "Ensure text can be zoomed to 200% in the browser without loss of content or functionality.",
  "1.4.5": "Replace images of text with real HTML text styled with CSS wherever possible.",
  "1.4.10": "Ensure content reflows into a single column at 320px width without requiring horizontal scrolling.",
  "1.4.11": "Ensure non-text UI components (input borders, icon buttons, focus rings) meet a 3:1 contrast ratio.",
  "1.4.12": "Allow users to override text spacing (line height, letter spacing, word spacing) without breaking layout.",
  "1.4.13": "Ensure hover/focus-triggered content is persistent, dismissible without moving focus, and hoverable.",
  "2.1.1": "Ensure all functionality is reachable and operable via keyboard; remove tabindex=\"-1\" from interactive elements.",
  "2.1.2": "Ensure keyboard focus is never trapped in a component; modal dialogs must include a keyboard-accessible close control.",
  "2.1.4": "Ensure single-key character shortcuts can be turned off, remapped, or activate only while the component has focus.",
  "2.2.1": "Give users the ability to turn off, adjust, or extend any time limits before they expire.",
  "2.2.2": "Provide a pause, stop, or hide mechanism for any moving, blinking, or auto-updating content.",
  "2.3.1": "Remove or slow down content that flashes more than 3 times per second to reduce seizure risk.",
  "2.4.1": "Add a visible skip navigation link so keyboard users can bypass repeated header and navigation blocks.",
  "2.4.2": "Add a descriptive, unique <title> element to every page that names both the page and the site.",
  "2.4.3": "Ensure focus order follows a logical reading sequence; avoid positive tabindex values above zero.",
  "2.4.4": "Write descriptive link text that is meaningful out of context; avoid generic phrases like 'click here'.",
  "2.4.5": "Provide at least two ways to reach each page (e.g., navigation menu, search, sitemap, or breadcrumbs).",
  "2.4.6": "Write headings and labels that clearly describe the purpose of the section or control they introduce.",
  "2.4.7": "Ensure visible keyboard focus is always present; never suppress the outline without providing an equivalent.",
  "2.4.11": "Ensure focused elements are not fully obscured by sticky headers, footers, or other fixed overlays.",
  "2.4.12": "Ensure no part of a focused component's focus indicator is hidden by author-created content.",
  "2.4.13": "Ensure focus indicators enclose the component with a minimum 2px perimeter and meet a 3:1 contrast ratio.",
  "2.5.1": "Provide a single-pointer alternative (e.g., button or tap) for every multi-finger or path-based gesture.",
  "2.5.2": "Do not trigger actions on the pointer down-event; allow cancellation by moving the pointer away before release.",
  "2.5.3": "Ensure the accessible name of every interactive control includes the visible label text.",
  "2.5.4": "Do not require device motion (shaking, tilting) as the only method for an action; provide a UI alternative.",
  "2.5.7": "Provide a single-pointer alternative (e.g., arrow buttons) for every drag-based interaction.",
  "2.5.8": "Ensure touch targets are at least 24×24 CSS pixels with sufficient spacing from adjacent targets.",
  "3.1.1": "Set a valid lang attribute on the <html> element to identify the primary language of the page.",
  "3.1.2": "Wrap passages in a different language with a lang attribute matching that language code.",
  "3.2.1": "Ensure focus alone does not trigger any context change such as form submission or navigation.",
  "3.2.2": "Do not auto-submit or navigate when a user changes a select or radio control; require an explicit action.",
  "3.2.3": "Keep navigation components in the same relative order across all pages of the site.",
  "3.2.4": "Label and name repeated components consistently wherever they appear across the site.",
  "3.2.6": "Include help or support contact information on every page that contains a form.",
  "3.3.1": "Identify input errors in text and associate the error message directly with the relevant field.",
  "3.3.2": "Provide a visible label or instruction for every input before the user submits the form.",
  "3.3.3": "When validation fails and the required format is known, suggest the correct format to the user.",
  "3.3.4": "Allow users to review, correct, and confirm submissions before finalizing legal or financial actions.",
  "3.3.7": "Do not ask users to re-enter information that was already collected and is not required for security.",
  "3.3.8": "Provide an accessible alternative (paste, biometrics, show-password) for any cognitive authentication test.",
  "4.1.1": "This criterion was removed in WCAG 2.2 and is no longer applicable.",
  "4.1.2": "Ensure every UI component exposes a programmatic name, role, and current state to assistive technologies.",
  "4.1.3": "Use aria-live regions or role=\"status\"/role=\"alert\" to announce status messages without moving keyboard focus.",
};
