export default {
  categories: {
    'senior-friendly': {
      title: 'Senior Friendliness',
      description: 'A comprehensive score based on audits for readability, ease of use, and a stable, non-confusing experience.',
      auditRefs: [
        { id: 'color-contrast', weight: 10 },
        { id: 'target-size', weight: 10 },
        { id: 'viewport', weight: 10 },
        { id: 'cumulative-layout-shift', weight: 10 },
        { id: 'text-font-audit', weight: 15 },
        { id: 'layout-brittle-audit', weight: 2 },
        { id: 'flesch-kincaid-audit', weight: 15 },
        { id: 'user-scalable-audit', weight: 4 },
        { id: 'horizontal-scroll-audit', weight: 3 },
        { id: 'text-size-adjust-audit', weight: 3 },
        { id: 'total-blocking-time', weight: 5 },
        { id: 'link-name', weight: 5 },
        { id: 'button-name', weight: 5 },
        { id: 'label', weight: 5 },
        { id: 'interactive-color-audit', weight: 5 },
        { id: 'is-on-https', weight: 2 },
        { id: 'dom-size', weight: 2 },
        { id: 'heading-order', weight: 2 },
        { id: 'errors-in-console', weight: 2 },
        { id: 'geolocation-on-start', weight: 2 },
        { id: 'image-alt', weight: 5 },
        { id: 'focus-traps', weight: 4 },
        { id: 'bypass', weight: 3 },
        { id: 'line-spacing-audit', weight: 5 },
        { id: 'autoplay-audit', weight: 3 },
      ],
    },
  },
};
